## Chennapragada. V. S. S. Mani Saketh
## AP19110010348
## CSE - C
## ML Assignment 6

1. Implement Naïve Bayes classifier for following datasets and evaluate the classification
performance. Draw the confusion matrix, compute accuracy, error and other measures as
applicable.
        a. The enjoy sports dataset
        b. The Iris dataset

In [1]:
# load the iris dataset
import numpy as np
from math import sqrt
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
#Importing Data
df = pd.read_csv('Enjoy sports - Sheet1.csv')
le = LabelEncoder()

label = le.fit_transform(df['Decision'])
df.drop('Decision', axis=1, inplace=True)
df["Decision"] = label

label = le.fit_transform(df['Outlook'])
df.drop('Outlook', axis=1, inplace=True)
df["Outlook"] = label

label = le.fit_transform(df['Temp.'])
df.drop('Temp.', axis=1, inplace=True)
df["Temp."] = label

label = le.fit_transform(df['Humidity'])
df.drop('Humidity', axis=1, inplace=True)
df["Humidity"] = label

label = le.fit_transform(df['Wind'])
df.drop('Wind', axis=1, inplace=True)
df["Wind"] = label

y = df['Decision']
X = df.drop(['Decision','Day'],axis = 1)
print("Y values after changing them from categorical to numerical")
print(y)
print("X values after changing them from categorical to numerical")
print(X)
# splitting X and y into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
# training the model on training set
gnb = GaussianNB()
gnb.fit(X_train, y_train)
# making predictions on the testing set
y_pred = gnb.predict(X_test)
# comparing actual response values (y_test) with predicted response values (y_pred)
print("Confusion Matrix : ")
print(confusion_matrix(y_test, y_pred))
print("\nGaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)
# 1. RMSE: Root Mean Squared Error
# 2. MAE: Mean Absolute Error
# 3. R-Squared Error
y_mean = np.mean(y)
rmse_nume = 0
mae_nume = 0
n = len(y_pred)
for i in y:
    j = 0
    if(j<n):
        rmse_nume += (i - y_pred[j])**2
        mae_nume += abs(i - y_pred[j])
        j = j+1
SSR = 0
SST = 0
for i in y:
    j = 0
    SST += (i-y_mean)**2
    if(j<n):
        SSR += (y_pred[j]-y_mean)**2
        j = j+1
R_Squared = SSR/SST
rmse = pow(rmse_nume/n,1/2)
mae = mae_nume/n
print("\nRoot Mean Squared Error for the given data is ", rmse)
print("\nMean Absolute Error for the given data is ",mae)
print("\nR-Squared for the given data is ",R_Squared)
print("\nClassification Report : ")
print(classification_report(y_test, y_pred))

Y values after changing them from categorical to numerical
0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: Decision, dtype: int32
X values after changing them from categorical to numerical
    Outlook  Temp.  Humidity  Wind
0         2      1         0     1
1         2      1         0     0
2         0      1         0     1
3         1      2         0     1
4         1      0         1     1
5         1      0         1     0
6         0      0         1     0
7         2      2         0     1
8         2      0         1     1
9         1      2         1     1
10        2      2         1     0
11        0      2         0     0
12        0      1         1     1
13        1      2         0     0
Confusion Matrix : 
[[1 0]
 [1 4]]

Gaussian Naive Bayes model accuracy(in %): 83.33333333333334

Root Mean Squared Error for the given data is  0.9128709291752769

Mean Absolute Error for the given data is  0.833333

In [2]:
# load the iris dataset
import numpy as np
from math import sqrt
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import metrics
iris = load_iris()
# store the feature matrix (X) and response vector (y)
X = iris.data
y = iris.target
# splitting X and y into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
# training the model on training set
gnb = GaussianNB()
gnb.fit(X_train, y_train)
# making predictions on the testing set
y_pred = gnb.predict(X_test)
# comparing actual response values (y_test) with predicted response values (y_pred)
print("Confusion Matrix : ")
print(confusion_matrix(y_test, y_pred))
print("\nGaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)
# 1. RMSE: Root Mean Squared Error
# 2. MAE: Mean Absolute Error
# 3. R-Squared Error
y_mean = np.mean(y)
rmse_nume = 0
mae_nume = 0
n = len(y_pred)
for i in y:
    j = 0
    if(j<n):
        rmse_nume += (i - y_pred[j])**2
        mae_nume += abs(i - y_pred[j])
        j = j+1
SSR = 0
SST = 0
for i in y:
    j = 0
    SST += (i-y_mean)**2
    if(j<n):
        SSR += (y_pred[j]-y_mean)**2
        j = j+1
R_Squared = SSR/SST
rmse = pow(rmse_nume/n,1/2)
mae = mae_nume/n
print("\nRoot Mean Squared Error for the given data is ", rmse)
print("\nMean Absolute Error for the given data is ",mae)
print("\nR-Squared for the given data is ",R_Squared)
print("\nClassification Report : ")
print(classification_report(y_test, y_pred))

Confusion Matrix : 
[[19  0  0]
 [ 0 19  2]
 [ 0  1 19]]

Gaussian Naive Bayes model accuracy(in %): 95.0

Root Mean Squared Error for the given data is  2.041241452319315

Mean Absolute Error for the given data is  2.5

R-Squared for the given data is  1.5

Classification Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.95      0.90      0.93        21
           2       0.90      0.95      0.93        20

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.95      0.95      0.95        60

