### Chennapragada. V. S. S. Mani Saketh
### AP19110010348
### CSE - C
### Machine Learning Practice Assignment - 1

## Write a python program to create a random array and compute the Covariance and Correlation Matrix.

#### Model 1

In [38]:
import numpy as np
import math
n = int(input("Enter the no. of data records: "))
m = int(input("Enter the no. of values in each data record: "))
a = []
for i in range(n):
    a.append(np.random.random())
b = []
for i in range(m):
    b.append(np.random.random())
def covariance(x, y):
  sum_x = 0
  mean_x = 0
  for i in x:
    sum_x += i
  mean_x = sum_x / len(x)

  sum_y = 0
  mean_y = 0
  for i in y:
    sum_y += i
  mean_y = sum_y / len(y)


  sum_corr = 0
  for i in range(len(x)):
    sum_corr += (x[i] - mean_x) * (y[i] - mean_y)
  c = sum_corr / len(x)-1
  return c
c = covariance(a,b)
print("\nThe covariance of x and y values are : \n")
print(c)

Enter the no. of data records: 4
Enter the no. of values in each data record: 4

The covariance of x and y values are : 

-0.9950102449523389


In [39]:
import numpy as np
import math
n = int(input("Enter the no. of data records: "))
m = int(input("Enter the no. of values in each data record: "))
a = []
for i in range(n):
    a.append(np.random.random())
b = []
for i in range(m):
    b.append(np.random.random())
def correlation(x, y):
  sum_x = 0
  mean_x = 0
  for i in x:
    sum_x += i
  mean_x = sum_x / len(x)

  sum_y = 0
  mean_y = 0
  for i in y:
    sum_y += i
  mean_y = sum_y / len(y)

  var_x = 0
  for i in x:
    var_x += (i - mean_x) ** 2
  
  var_y = 0
  for i in y:
    var_y += (i - mean_y) ** 2
  
  var_sum = math.sqrt(var_x * var_y)

  sum_corr = 0
  for i in range(len(x)):
    sum_corr += (x[i] - mean_x) * (y[i] - mean_y)
  c = sum_corr / var_sum
  return c
c = correlation(a,b)
print("\nThe correlation of x and y values are : \n")
print(c)

Enter the no. of data records: 4
Enter the no. of values in each data record: 4

The correlation of x and y values are : 

0.06467619577817867


#### Model 2

In [40]:
n = int(input("Enter the no. of data records: "))
m = int(input("Enter the no. of values in each data record: "))
a = np.random.rand(n, m)
b = np.cov(a)
print("\nThe Covariance matrix is : \n")
print(b)


Enter the no. of data records: 4
Enter the no. of values in each data record: 4

The Covariance matrix is : 

[[ 0.08153982 -0.05983211 -0.01338012  0.04040694]
 [-0.05983211  0.15630466  0.02938019  0.04828779]
 [-0.01338012  0.02938019  0.0915606   0.02999455]
 [ 0.04040694  0.04828779  0.02999455  0.08025108]]


In [42]:
n = int(input("Enter the no. of data records: "))
m = int(input("Enter the no. of values in each data record: "))
a = []
for i in range(n):
    a.append(np.random.random())
b = []
for i in range(m):
    b.append(np.random.random())
print("\nThe Correlation matrix is : \n")
np.corrcoef(a,b)

Enter the no. of data records: 4
Enter the no. of values in each data record: 4

The Correlation matrix is : 



array([[ 1.        , -0.03858977],
       [-0.03858977,  1.        ]])

#### Model 3 - Includes all questions

In [45]:
import numpy as np
import pandas as pd
import random
# Creating random arrays
x = np.random.rand(5,5)
y = np.random.rand(5,5)
# Calulating center of mass or average
avg = (np.mean(x),np.mean(y))
# Calculating the variance
x_var = np.sum(np.square (x - np.mean(x)))/((np.shape(x)[0]*np.shape(x)[1])-1)
y_var = np.sum(np.square (y - np.mean(y)))/((np.shape(y)[0]*np.shape(y)[1])-1)
# Covariance of single value
cov_x_y = np.sum((x-np.mean(x))*(y-np.mean(y)))/((np.shape(x)[0]*np.shape(x)[1])-1)
print("The Covariance Value")
print(cov_x_y)
#Calculating covariance matrix
cov_matrix = np.array([[x_var,cov_x_y],[cov_x_y,y_var]])
print("\nThe Covariance Matrix")
print(cov_matrix)
#Calculating coreelation coefficient
correlation_coeff = cov_x_y/(np.sqrt(x_var*y_var)*np.sqrt(y_var))
print("\nThe Correlation Value")
print(correlation_coeff)
#Calculating correlation matrix
corr_mat = [[x_var/x_var,correlation_coeff],[correlation_coeff,y_var/y_var]]
print("\nThe Correlation Matrix")
print(corr_mat)
#Calcuating euclidean distance 
euc_distance = np.sqrt(np.square(x-y))
print("\nThe euclidean distance")
print(euc_distance)

The Covariance Value
0.014861463418246255

The Covariance Matrix
[[0.08614062 0.01486146]
 [0.01486146 0.08915013]]

The Correlation Value
0.5679833550567305

The Correlation Matrix
[[1.0, 0.5679833550567305], [0.5679833550567305, 1.0]]

The euclidean distance
[[0.20507108 0.32041474 0.01395074 0.38294888 0.43772889]
 [0.29412813 0.6540955  0.02864339 0.42616919 0.03344581]
 [0.06702835 0.16635895 0.31953804 0.18685976 0.19136519]
 [0.41418227 0.45167423 0.02510039 0.83900002 0.07421288]
 [0.2483359  0.33041255 0.53182233 0.78193414 0.10564651]]
